const equipos = [
 {id:'EQ-001',codigo:'AFM-S1D-001',tipo:'Jumbo Frontonero',marca:'Epiroc',modelo:'Boomer S1D',serie:'S1D-2026-001',faena:'El Teniente',contrato:'P4600',responsable:'Operador Ejemplo 1',estadoEquipo:'Operativo',estadoCert:'Vigente',emision:'2026-05-19',vencimiento:'2026-11-15',pdf:'certificados/certificado_EQ-001.pdf',qr:'verificar.html?id=EQ-001',foto:'assets/equipo_placeholder.svg'},
 {id:'EQ-002',codigo:'AFM-S7D-002',tipo:'Simba Radial',marca:'Epiroc',modelo:'Simba S7D',serie:'S7D-2026-002',faena:'El Teniente',contrato:'P4600',responsable:'Operador Ejemplo 2',estadoEquipo:'Operativo',estadoCert:'Por vencer',emision:'2026-02-08',vencimiento:'2026-06-13',pdf:'certificados/certificado_EQ-002.pdf',qr:'verificar.html?id=EQ-002',foto:'assets/equipo_placeholder.svg'},
 {id:'EQ-003',codigo:'AFM-BOL-003',tipo:'Boltec',marca:'Epiroc',modelo:'Boltec M',serie:'BOL-2026-003',faena:'Salvador',contrato:'Contrato Demo',responsable:'Operador Ejemplo 3',estadoEquipo:'Mantención',estadoCert:'Vencido',emision:'2025-04-14',vencimiento:'2026-04-29',pdf:'certificados/certificado_EQ-003.pdf',qr:'verificar.html?id=EQ-003',foto:'assets/equipo_placeholder.svg'}
];
const $=id=>document.getElementById(id);
function slug(s){return s.replaceAll(' ','-')}
function initFaenas(){[...new Set(equipos.map(e=>e.faena))].forEach(f=>{let o=document.createElement('option');o.textContent=f;$('faena').appendChild(o)})}
function render(){const q=$('q').value.toLowerCase(), est=$('estado').value, fa=$('faena').value; const data=equipos.filter(e=>(!est||e.estadoCert==est)&&(!fa||e.faena==fa)&&JSON.stringify(e).toLowerCase().includes(q)); $('grid').innerHTML=data.map(e=>`<article class="card"><img src="${e.foto}" alt="${e.modelo}"><div class="body"><span class="tag ${slug(e.estadoCert)}">${e.estadoCert}</span><h2>${e.modelo}</h2><p><b>${e.codigo}</b> · ${e.tipo}</p><div class="meta"><span>Faena<br><b>${e.faena}</b></span><span>Contrato<br><b>${e.contrato}</b></span><span>Serie<br><b>${e.serie}</b></span><span>Vence<br><b>${e.vencimiento}</b></span><span>Estado equipo<br><b>${e.estadoEquipo}</b></span><span>Responsable<br><b>${e.responsable}</b></span></div><div class="actions"><a href="${e.pdf}" target="_blank">Ver certificado</a><a class="secondary" href="${e.qr}" target="_blank">Validar QR</a></div></div></article>`).join(''); $('kTotal').textContent=equipos.length; $('kVig').textContent=equipos.filter(e=>e.estadoCert=='Vigente').length; $('kPor').textContent=equipos.filter(e=>e.estadoCert=='Por vencer').length; $('kVen').textContent=equipos.filter(e=>e.estadoCert=='Vencido').length;}
['q','estado','faena'].forEach(id=>$(id).addEventListener('input',render)); initFaenas(); render();
