const EQUIPOS = [
  {
    "id": "EQ-001",
    "equipo": "JUMBO J-187",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-002",
    "equipo": "JUMBO S1D J-133",
    "estado": "Operativo",
    "observacion": "Flexible de retorno avance",
    "marca": "Epiroc",
    "modelo": "Boomer S1D",
    "serie": "TMG25URE0133",
    "rig": "8999795900",
    "fecha": "10-07-2025",
    "tipo": "FOPS/ROPS ISO 3449:2008 / ISO 3471:2008",
    "certificado": "certificados/Fops Rops S1D-DH 8999795900.pdf"
  },
  {
    "id": "EQ-003",
    "equipo": "JUMBO DD311D J-587",
    "estado": "Operativo",
    "observacion": "",
    "marca": "Sandvik",
    "modelo": "DD311D",
    "serie": "L22D7587",
    "rig": "L22D7587",
    "fecha": "19-05-2025",
    "tipo": "Cabina FOPS ISO 3449:2005 Nivel II / ROPS ISO 3471:1994",
    "certificado": "certificados/Certificados DD311D L22D7587 Cabina.pdf"
  },
  {
    "id": "EQ-004",
    "equipo": "JUMBO S7D J-163",
    "estado": "Operativo",
    "observacion": "",
    "marca": "Epiroc",
    "modelo": "Simba S7D",
    "serie": "TMG25URE0163",
    "rig": "8999797800",
    "fecha": "21-08-2025",
    "tipo": "FOPS/ROPS ISO 3449:2008 / ISO 3471:2008",
    "certificado": "certificados/Fops Rops S7D 8999797800.pdf"
  },
  {
    "id": "EQ-005",
    "equipo": "BOLTEC",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-006",
    "equipo": "Jumbo Boltec J-381",
    "estado": "F/S",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-007",
    "equipo": "MANIPULADOR MAT-474",
    "estado": "Operativo",
    "observacion": "",
    "marca": "JCB",
    "modelo": "533 105 T",
    "serie": "JCB5AH2G**3465474",
    "rig": "3465474",
    "fecha": "Febrero 2025",
    "tipo": "Ergonomía, seguridad, ROPS/FOPS",
    "certificado": "certificados/Ergonomia 3465474.pdf"
  },
  {
    "id": "EQ-008",
    "equipo": "MANIPULADOR MAT-336",
    "estado": "Operativo",
    "observacion": "",
    "marca": "JCB",
    "modelo": "533 105 T",
    "serie": "JCB5AH2G**3465336",
    "rig": "3465336",
    "fecha": "Febrero 2025",
    "tipo": "Ergonomía, seguridad, ROPS/FOPS",
    "certificado": "certificados/Ergonomia 3465336.pdf"
  },
  {
    "id": "EQ-009",
    "equipo": "MANIPULADOR MAT-319",
    "estado": "Operativo",
    "observacion": "",
    "marca": "JCB",
    "modelo": "533 105 T",
    "serie": "JCB5AH2G**3465319",
    "rig": "3465319",
    "fecha": "Febrero 2025",
    "tipo": "Ergonomía, seguridad, ROPS/FOPS",
    "certificado": "certificados/Ergonomia 3465319.pdf"
  },
  {
    "id": "EQ-010",
    "equipo": "MANIPULADOR MAT-047",
    "estado": "Operativo",
    "observacion": "",
    "marca": "JCB",
    "modelo": "533 105 T",
    "serie": "JCB5AH2G**3465047",
    "rig": "3465047",
    "fecha": "Febrero 2025",
    "tipo": "Ergonomía, seguridad, ROPS/FOPS",
    "certificado": "certificados/Ergonomia 3465047.pdf"
  },
  {
    "id": "EQ-011",
    "equipo": "MANIPULADOR MAT-869",
    "estado": "F/S",
    "observacion": "",
    "marca": "JCB",
    "modelo": "533 105 T",
    "serie": "JCB5AH2G**3464869",
    "rig": "3464869",
    "fecha": "Febrero 2025",
    "tipo": "Ergonomía, seguridad, ROPS/FOPS",
    "certificado": "certificados/Ergonomia 3464869.pdf"
  },
  {
    "id": "EQ-012",
    "equipo": "MANIPULADOR MAT-933",
    "estado": "Operativo",
    "observacion": "",
    "marca": "JCB",
    "modelo": "533 105 T",
    "serie": "JCB5AH2G**3464933",
    "rig": "3464933",
    "fecha": "Febrero 2025",
    "tipo": "Ergonomía, seguridad, ROPS/FOPS",
    "certificado": "certificados/Ergonomia 3464933.pdf"
  },
  {
    "id": "EQ-013",
    "equipo": "MANIPULADOR MAT-160",
    "estado": "Operativo",
    "observacion": "",
    "marca": "JCB",
    "modelo": "533 105 T",
    "serie": "JCB5AH2G**3465160",
    "rig": "3465160",
    "fecha": "Febrero 2025",
    "tipo": "Ergonomía, seguridad, ROPS/FOPS",
    "certificado": "certificados/Ergonomia 3465160.pdf"
  },
  {
    "id": "EQ-014",
    "equipo": "MANIPULADOR MAT-747",
    "estado": "Operativo",
    "observacion": "",
    "marca": "JCB",
    "modelo": "533 105 T",
    "serie": "JCB5AH2G**3466747",
    "rig": "3466747",
    "fecha": "Febrero 2025",
    "tipo": "Ergonomía, seguridad, ROPS/FOPS",
    "certificado": "certificados/Ergonomia 3466747.pdf"
  },
  {
    "id": "EQ-015",
    "equipo": "MANIPULADOR MAT-512",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-016",
    "equipo": "MANIPULADOR MAT-757",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-017",
    "equipo": "MANIPULADOR MAT-891",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-018",
    "equipo": "MANIPULADOR MAT-660",
    "estado": "F/S",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-019",
    "equipo": "RETROEXCAVADORA 264",
    "estado": "Operativo",
    "observacion": "F/S tarjeta verde",
    "marca": "JCB",
    "modelo": "3CX-ECO-92HP-MC_CL",
    "serie": "JCB3CX4TER3326264",
    "rig": "3326264",
    "fecha": "25-02-2025",
    "tipo": "Ergonomía, seguridad, ROPS/FOPS",
    "certificado": "certificados/Ergonomia 3326264.pdf"
  },
  {
    "id": "EQ-020",
    "equipo": "RETROEXCAVADORA 385",
    "estado": "Operativo",
    "observacion": "",
    "marca": "JCB",
    "modelo": "3CX-ECO-92HP-MC_CL",
    "serie": "JCB3CX4TLR3439385",
    "rig": "3439385",
    "fecha": "28-02-2025",
    "tipo": "Ergonomía, seguridad, ROPS/FOPS",
    "certificado": "certificados/Ergonomia 3439385.pdf"
  },
  {
    "id": "EQ-021",
    "equipo": "ROBOSHOT 231",
    "estado": "Operativo",
    "observacion": "",
    "marca": "Normet",
    "modelo": "Roboshot",
    "serie": "EQA0231",
    "rig": "EQA0231",
    "fecha": "15-05-2025",
    "tipo": "Cabina hermética climatizada FOPS ISO 3449:2005 / ROPS ISO 3471:2008",
    "certificado": "certificados/1 CERTIFICADO CABINA EQA0231.pdf"
  },
  {
    "id": "EQ-022",
    "equipo": "ROBOSHOT 048",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-023",
    "equipo": "LHD 033",
    "estado": "Operativo",
    "observacion": "",
    "marca": "Epiroc",
    "modelo": "Scooptram ST1030",
    "serie": "CNN25URE0033",
    "rig": "8997991900",
    "fecha": "21-03-2025",
    "tipo": "FOPS/ROPS ISO 3449:2005 / ISO 3471:2008",
    "certificado": "certificados/Certificado FOPS- ROPS.pdf"
  },
  {
    "id": "EQ-024",
    "equipo": "LHD 043",
    "estado": "Operativo",
    "observacion": "",
    "marca": "Atlas Copco",
    "modelo": "ST1030",
    "serie": "LHD043",
    "rig": "ST1030",
    "fecha": "02-12-2008",
    "tipo": "ROPS/FOPS ISO 3471:2008 / ISO 3449:2005 Nivel II",
    "certificado": "certificados/ROPS FOPS Test Certificate ST1030 LHD043.pdf"
  },
  {
    "id": "EQ-025",
    "equipo": "ACUÑADOR 427",
    "estado": "Operativo",
    "observacion": "",
    "marca": "Resemin",
    "modelo": "Scalemin HT",
    "serie": "JMC-1427 / equipo JMC-1405",
    "rig": "JMC-1427",
    "fecha": "05-02-2025",
    "tipo": "Inspección FOPS/ROPS Bureau Veritas",
    "certificado": "certificados/6. JMC-1427 CERTIFICADA FOPS ROPS.pdf"
  },
  {
    "id": "EQ-026",
    "equipo": "COMPRESOR K95",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-027",
    "equipo": "COMPRESOR 404",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-028",
    "equipo": "COMPRESOR",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-029",
    "equipo": "B. HORMIGON 978",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-030",
    "equipo": "GENERADOR 009",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-031",
    "equipo": "GENERADOR 011",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-032",
    "equipo": "GENERADOR 012",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-033",
    "equipo": "BROKK 520 D",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-034",
    "equipo": "MIXER 01",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-035",
    "equipo": "MIXER 02",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  },
  {
    "id": "EQ-036",
    "equipo": "MINICARGADOR",
    "estado": "Operativo",
    "observacion": "",
    "marca": "",
    "modelo": "",
    "serie": "",
    "rig": "",
    "fecha": "",
    "tipo": "",
    "certificado": ""
  }
];
