const EQUIPOS = [
  {
    "ID Equipo": "XTM-JUMBO-133",
    "Equipo": "JUMBO S1D BOOMER",
    "Familia": "Jumbo",
    "Marca": "Epiroc",
    "Modelo": "Boomer S1D",
    "Serie/VIN": "TMG25URE0133",
    "Rig/Patente": "8999795900",
    "Tipo Certificado": "FOPS/ROPS",
    "Estado": "Vigente",
    "Emisión": "10-07-2025",
    "Vencimiento": "10-07-2026",
    "Archivo Certificado": "Fops Rops S1D-DH 8999795900(1).pdf",
    "URL Local": "certificados/Fops Rops S1D-DH 8999795900(1).pdf",
    "QR": "qr/XTM-JUMBO-133.png"
  },
  {
    "ID Equipo": "XTM-JUMBO-163",
    "Equipo": "JUMBO SIMBA S7D",
    "Familia": "Jumbo",
    "Marca": "Epiroc",
    "Modelo": "Simba S7D",
    "Serie/VIN": "TMG25URE0163",
    "Rig/Patente": "8999797800",
    "Tipo Certificado": "FOPS/ROPS",
    "Estado": "Vigente",
    "Emisión": "21-08-2025",
    "Vencimiento": "21-08-2026",
    "Archivo Certificado": "Fops Rops S7D 8999797800(1).pdf",
    "URL Local": "certificados/Fops Rops S7D 8999797800(1).pdf",
    "QR": "qr/XTM-JUMBO-163.png"
  },
  {
    "ID Equipo": "XTM-JUMBO-187",
    "Equipo": "JUMBO S1D BOOMER",
    "Familia": "Jumbo",
    "Marca": "Epiroc",
    "Modelo": "Boomer S1D",
    "Serie/VIN": "",
    "Rig/Patente": "",
    "Tipo Certificado": "Pendiente certificado",
    "Estado": "Pendiente",
    "Emisión": "",
    "Vencimiento": "",
    "Archivo Certificado": "",
    "URL Local": "",
    "QR": "qr/XTM-JUMBO-187.png"
  },
  {
    "ID Equipo": "XTM-JUMBO-587",
    "Equipo": "JUMBO DD311D",
    "Familia": "Jumbo",
    "Marca": "Sandvik",
    "Modelo": "DD311D",
    "Serie/VIN": "L22D7587",
    "Rig/Patente": "",
    "Tipo Certificado": "Cabina FOPS/ROPS",
    "Estado": "Vigente",
    "Emisión": "19-05-2025",
    "Vencimiento": "19-05-2026",
    "Archivo Certificado": "Certificados DD311D L22D7587 Cabina(1).pdf",
    "URL Local": "certificados/Certificados DD311D L22D7587 Cabina(1).pdf",
    "QR": "qr/XTM-JUMBO-587.png"
  },
  {
    "ID Equipo": "XTM-JUMBO-381",
    "Equipo": "JUMBO BOLTEC",
    "Familia": "Jumbo",
    "Marca": "Epiroc",
    "Modelo": "Boltec MC",
    "Serie/VIN": "TMG20URE0381",
    "Rig/Patente": "8999473200",
    "Tipo Certificado": "FOPS/ROPS + Supresión + Gases + Aire + Lámina",
    "Estado": "Vigente",
    "Emisión": "06-02-2026",
    "Vencimiento": "06-02-2027",
    "Archivo Certificado": "BOLTEC M J-381.pdf",
    "URL Local": "certificados/BOLTEC M J-381.pdf",
    "QR": "qr/XTM-JUMBO-381.png"
  },
  {
    "ID Equipo": "XTM-LHD-033",
    "Equipo": "SCOOP ST1030",
    "Familia": "LHD",
    "Marca": "Epiroc / Atlas Copco",
    "Modelo": "Scooptram ST1030",
    "Serie/VIN": "CNN25URE0033",
    "Rig/Patente": "8997991900",
    "Tipo Certificado": "FOPS/ROPS",
    "Estado": "Vigente",
    "Emisión": "21-03-2025",
    "Vencimiento": "21-03-2026",
    "Archivo Certificado": "Certificado FOPS- ROPS(1).pdf",
    "URL Local": "certificados/Certificado FOPS- ROPS(1).pdf",
    "QR": "qr/XTM-LHD-033.png"
  },
  {
    "ID Equipo": "XTM-LHD-043",
    "Equipo": "SCOOP ST1030",
    "Familia": "LHD",
    "Marca": "Atlas Copco",
    "Modelo": "Scooptram ST1030",
    "Serie/VIN": "",
    "Rig/Patente": "",
    "Tipo Certificado": "ROPS/FOPS Test Certificate",
    "Estado": "Vigente",
    "Emisión": "02-12-2008",
    "Vencimiento": "Revisión documental",
    "Archivo Certificado": "ROPS FOPS Test Certificate ST1030 LHD043(3).pdf",
    "URL Local": "certificados/ROPS FOPS Test Certificate ST1030 LHD043(3).pdf",
    "QR": "qr/XTM-LHD-043.png"
  },
  {
    "ID Equipo": "XTM-MANI-047",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "JCB5AH2GTR3465047",
    "Rig/Patente": "",
    "Tipo Certificado": "Ergonomía / FOPS / ROPS",
    "Estado": "Vigente",
    "Emisión": "25-02-2025",
    "Vencimiento": "25-02-2026",
    "Archivo Certificado": "Ergonomia 3465047(1).pdf",
    "URL Local": "certificados/Ergonomia 3465047(1).pdf",
    "QR": "qr/XTM-MANI-047.png"
  },
  {
    "ID Equipo": "XTM-MANI-869",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "JCB5AH2GKR3464869",
    "Rig/Patente": "",
    "Tipo Certificado": "Ergonomía / FOPS / ROPS",
    "Estado": "Vigente",
    "Emisión": "25-02-2025",
    "Vencimiento": "25-02-2026",
    "Archivo Certificado": "Ergonomia 3464869(1).pdf",
    "URL Local": "certificados/Ergonomia 3464869(1).pdf",
    "QR": "qr/XTM-MANI-869.png"
  },
  {
    "ID Equipo": "XTM-MANI-160",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "JCB5AH2GER3465160",
    "Rig/Patente": "",
    "Tipo Certificado": "Ergonomía / FOPS / ROPS",
    "Estado": "Vigente",
    "Emisión": "25-02-2025",
    "Vencimiento": "25-02-2026",
    "Archivo Certificado": "Ergonomia 3465160(1).pdf",
    "URL Local": "certificados/Ergonomia 3465160(1).pdf",
    "QR": "qr/XTM-MANI-160.png"
  },
  {
    "ID Equipo": "XTM-MANI-933",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "JCB5AH2GCR3464933",
    "Rig/Patente": "",
    "Tipo Certificado": "Ergonomía / FOPS / ROPS",
    "Estado": "Vigente",
    "Emisión": "25-02-2025",
    "Vencimiento": "25-02-2026",
    "Archivo Certificado": "Ergonomia 3464933(1).pdf",
    "URL Local": "certificados/Ergonomia 3464933(1).pdf",
    "QR": "qr/XTM-MANI-933.png"
  },
  {
    "ID Equipo": "XTM-MANI-747",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "JCB5AH2GTR3466747",
    "Rig/Patente": "",
    "Tipo Certificado": "Ergonomía / FOPS / ROPS",
    "Estado": "Vigente",
    "Emisión": "28-02-2025",
    "Vencimiento": "28-02-2026",
    "Archivo Certificado": "Ergonomia 3466747(1).pdf",
    "URL Local": "certificados/Ergonomia 3466747(1).pdf",
    "QR": "qr/XTM-MANI-747.png"
  },
  {
    "ID Equipo": "XTM-MANI-336",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "JCB5AH2GER3465336",
    "Rig/Patente": "",
    "Tipo Certificado": "Ergonomía / FOPS / ROPS",
    "Estado": "Vigente",
    "Emisión": "28-02-2025",
    "Vencimiento": "28-02-2026",
    "Archivo Certificado": "Ergonomia 3465336(1).pdf",
    "URL Local": "certificados/Ergonomia 3465336(1).pdf",
    "QR": "qr/XTM-MANI-336.png"
  },
  {
    "ID Equipo": "XTM-MANI-319",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "JCB5AH2GER3465319",
    "Rig/Patente": "",
    "Tipo Certificado": "Ergonomía / FOPS / ROPS",
    "Estado": "Vigente",
    "Emisión": "28-02-2025",
    "Vencimiento": "28-02-2026",
    "Archivo Certificado": "Ergonomia 3465319(1).pdf",
    "URL Local": "certificados/Ergonomia 3465319(1).pdf",
    "QR": "qr/XTM-MANI-319.png"
  },
  {
    "ID Equipo": "XTM-MANI-474",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "JCB5AH2GCR3465474",
    "Rig/Patente": "",
    "Tipo Certificado": "Ergonomía / FOPS / ROPS",
    "Estado": "Vigente",
    "Emisión": "28-02-2025",
    "Vencimiento": "28-02-2026",
    "Archivo Certificado": "Ergonomia 3465474(1).pdf",
    "URL Local": "certificados/Ergonomia 3465474(1).pdf",
    "QR": "qr/XTM-MANI-474.png"
  },
  {
    "ID Equipo": "XTM-MANI-512",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "",
    "Rig/Patente": "",
    "Tipo Certificado": "Pendiente certificado",
    "Estado": "Pendiente",
    "Emisión": "",
    "Vencimiento": "",
    "Archivo Certificado": "",
    "URL Local": "",
    "QR": "qr/XTM-MANI-512.png"
  },
  {
    "ID Equipo": "XTM-MANI-757",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "",
    "Rig/Patente": "",
    "Tipo Certificado": "Pendiente certificado",
    "Estado": "Pendiente",
    "Emisión": "",
    "Vencimiento": "",
    "Archivo Certificado": "",
    "URL Local": "",
    "QR": "qr/XTM-MANI-757.png"
  },
  {
    "ID Equipo": "XTM-MANI-891",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "",
    "Rig/Patente": "",
    "Tipo Certificado": "Pendiente certificado",
    "Estado": "Pendiente",
    "Emisión": "",
    "Vencimiento": "",
    "Archivo Certificado": "",
    "URL Local": "",
    "QR": "qr/XTM-MANI-891.png"
  },
  {
    "ID Equipo": "XTM-MANI-660",
    "Equipo": "MANIPULADOR TELESCOPICO",
    "Familia": "Manipulador",
    "Marca": "JCB",
    "Modelo": "533-105 T",
    "Serie/VIN": "",
    "Rig/Patente": "",
    "Tipo Certificado": "Pendiente certificado",
    "Estado": "Pendiente",
    "Emisión": "",
    "Vencimiento": "",
    "Archivo Certificado": "",
    "URL Local": "",
    "QR": "qr/XTM-MANI-660.png"
  },
  {
    "ID Equipo": "XTM-RETRO-264",
    "Equipo": "RETROEXCAVADORA",
    "Familia": "Retroexcavadora",
    "Marca": "JCB",
    "Modelo": "3CX-ECO-92HP-MC_CL",
    "Serie/VIN": "JCB3CX4TER3326264",
    "Rig/Patente": "",
    "Tipo Certificado": "Ergonomía / FOPS / ROPS",
    "Estado": "Vigente",
    "Emisión": "25-02-2025",
    "Vencimiento": "25-02-2026",
    "Archivo Certificado": "Ergonomia 3326264(1).pdf",
    "URL Local": "certificados/Ergonomia 3326264(1).pdf",
    "QR": "qr/XTM-RETRO-264.png"
  },
  {
    "ID Equipo": "XTM-RETRO-385",
    "Equipo": "RETROEXCAVADORA",
    "Familia": "Retroexcavadora",
    "Marca": "JCB",
    "Modelo": "3CX-ECO-92HP-MC_CL",
    "Serie/VIN": "JCB3CX4TLR3439385",
    "Rig/Patente": "",
    "Tipo Certificado": "Ergonomía / FOPS / ROPS",
    "Estado": "Vigente",
    "Emisión": "28-02-2025",
    "Vencimiento": "28-02-2026",
    "Archivo Certificado": "Ergonomia 3439385(1).pdf",
    "URL Local": "certificados/Ergonomia 3439385(1).pdf",
    "QR": "qr/XTM-RETRO-385.png"
  },
  {
    "ID Equipo": "XTM-ROBOSHOT-231",
    "Equipo": "ROBOSHOT ALPHA 30",
    "Familia": "Shotcrete",
    "Marca": "Normet",
    "Modelo": "Roboshot Alpha 30",
    "Serie/VIN": "EQA0231",
    "Rig/Patente": "",
    "Tipo Certificado": "Cabina FOPS/ROPS",
    "Estado": "Vigente",
    "Emisión": "15-05-2025",
    "Vencimiento": "15-05-2026",
    "Archivo Certificado": "1 CERTIFICADO CABINA EQA0231(1).pdf",
    "URL Local": "certificados/1 CERTIFICADO CABINA EQA0231(1).pdf",
    "QR": "qr/XTM-ROBOSHOT-231.png"
  },
  {
    "ID Equipo": "XTM-ROBOSHOT-048",
    "Equipo": "ROBOSHOT ALPHA 20",
    "Familia": "Shotcrete",
    "Marca": "Normet",
    "Modelo": "Roboshot Alpha 20",
    "Serie/VIN": "ELA1045",
    "Rig/Patente": "",
    "Tipo Certificado": "Cabina FOPS/ROPS",
    "Estado": "Vigente",
    "Emisión": "10-11-2025",
    "Vencimiento": "10-11-2026",
    "Archivo Certificado": "1 CERTIFICADO CABINA ELA1048.pdf",
    "URL Local": "certificados/1 CERTIFICADO CABINA ELA1048.pdf",
    "QR": "qr/XTM-ROBOSHOT-048.png"
  },
  {
    "ID Equipo": "XTM-MIX-132",
    "Equipo": "MIXER",
    "Familia": "Mixer",
    "Marca": "",
    "Modelo": "Mixer",
    "Serie/VIN": "",
    "Rig/Patente": "",
    "Tipo Certificado": "Pendiente certificado",
    "Estado": "Pendiente",
    "Emisión": "",
    "Vencimiento": "",
    "Archivo Certificado": "",
    "URL Local": "",
    "QR": "qr/XTM-MIX-132.png"
  },
  {
    "ID Equipo": "XTM-MIX-152",
    "Equipo": "MIXER",
    "Familia": "Mixer",
    "Marca": "",
    "Modelo": "Mixer",
    "Serie/VIN": "",
    "Rig/Patente": "",
    "Tipo Certificado": "Pendiente certificado",
    "Estado": "Pendiente",
    "Emisión": "",
    "Vencimiento": "",
    "Archivo Certificado": "",
    "URL Local": "",
    "QR": "qr/XTM-MIX-152.png"
  },
  {
    "ID Equipo": "XTM-ACUÑADOR-427",
    "Equipo": "ACUÑADOR SCALEMIN HT",
    "Familia": "Acuñador",
    "Marca": "Resemin",
    "Modelo": "Scalemin HT",
    "Serie/VIN": "JMC-1427 / JMC-1405",
    "Rig/Patente": "",
    "Tipo Certificado": "Inspección FOPS/ROPS",
    "Estado": "Vigente",
    "Emisión": "05-02-2025",
    "Vencimiento": "05-02-2026",
    "Archivo Certificado": "6. JMC-1427 CERTIFICADA FOPS ROPS(1).pdf",
    "URL Local": "certificados/6. JMC-1427 CERTIFICADA FOPS ROPS(1).pdf",
    "QR": "qr/XTM-ACUÑADOR-427.png"
  }
];
